---
title: "RMark Data Formatting"
format: html
editor: visual
---

Load packages and data

```{r}

library(tidyverse)
library(RMark)

binary_ch <- read.csv("Binary_Capture_History.csv", colClasses = c("ch" = "character"))

full_capture_data <- read.csv("Capture_Data.csv")

```

Add frog sex to my binary capture history data frame to model survival by sex. 

```{r}

ch_sex <- binary_ch %>% 
  left_join(full_capture_data, by = "PIT_TagCode") %>% 
  select(PIT_TagCode, ch, frog_sex)

ch_sex$frog_sex <- as.factor(ch_sex$frog_sex)

ch_sex <- ch_sex %>%
  mutate(frog_sex = ifelse(frog_sex == "M", 1, 0))



```

Define time intervals

```{r}

# Intervals in days between primary periods
time.intervals <- c(0,0,33,0,0,54,0,0,271,0,0,32,0,0,55,0,0,299,0,0,25,0,0,26,0,0,320,0,0,26,0,0,26,0,0,278,0,0,19,0,0,26,0,0,26,0)

```

Process Data and make design data

```{r}

M_sex_data <- process.data(data = ch_sex,
                  model = "Robust",
                  time.intervals = time.intervals)

sex_design_data <- make.design.data(M_sex_data)

```

```{r}

mod_sex <- mark(M_sex_data, sex_design_data, model = "Robust",
              model.parameters = list(
                S = list(formula = ~ time + frog_sex),  # Survival
                p = list(formula = ~ session),  # Capture probability varies by session
                c = list(formula = ~ session),  # Recapture probability varies by session
                GammaPrime = list(formula = ~ time), 
                GammaDoublePrime = list(formula = ~ time)
              ))

```
```{r}

mod_sex$results$derived$`N Population Size`


```








