---
title: "Mossy_mrmr_model"
output: html_document
date: "2024-09-12"
---

Load packages 

```{r}

library(dplyr)
library(readr)
library(tibble)
library(rstan)
library(mrmr)

```

Load and format data

```{r}

# Load .csv of all captures from the Mossy Pond CMR study period
captures <- read.csv("Capture_Data.csv")

# Remove "00:00:00 EDT" from Date column for compatibility with 'mrmr' 
captures$Date <- gsub("00:00:00 EDT","", capture_full_data$Date)

# Convert 'Date' variable to object class date
captures$Date <- as.Date(capture_full_data$Date, format = "%a %b %d  %Y")

# Change variable names for compatibility with 'mrmr' 
names(captures)[names(capture_full_data) == "Date"] <- "survey_date"
names(captures)[names(capture_full_data) == "PIT_TagCode"] <- "pit_tag_id"

```


```{r}
# Remove "00:00:00 EDT" from Date column because it is the same in all and doesn't add anything
capture_full_data$Date <- gsub("00:00:00 EDT","", capture_full_data$Date)

# Convert Date variable from character string to date object (account for extra space before Y)
capture_full_data$Date <- as.Date(capture_full_data$Date, format = "%a %b %d  %Y")

# change names to mrmr format
names(capture_full_data)[names(capture_full_data) == "Date"] <- "survey_date"
names(capture_full_data)[names(capture_full_data) == "PIT_TagCode"] <- "pit_tag_id"

captures <- unique(capture_full_data[ ,c(3, 5)])
captures$survey_date <- as.character(captures$survey_date)
captures$pit_tag_id <- as.character(captures$pit_tag_id)

# load surveys .csv I made externally
surveys <- read.csv("survey.csv")

surveys$survey_date <- as.character(surveys$survey_date)
surveys$primary_period <- as.integer(surveys$primary_period)
surveys$secondary_period <- as.integer(surveys$secondary_period)

# run the clean data function
data1 <- clean_data(captures,
           surveys)

# fit model

mrmr_mossy_mod_2.5 <- fit_model(data1,
                                chains = 3, 
                                iter_sampling = 1000, 
                                iter_warmup = 400)

```


## Save the model summary to an object

```{r}

# Save the m_fit summary to an object
mod2.5_summary <- mrmr_mossy_mod_2.5$m_fit$summary()

view(mod2.5_summary)


```
