---
title: "Mossy_custom_mrmr"
output: html_document
date: "2024-11-13"
---

# custom TVD mrmr model with MP data

```{r}
library(dplyr)
library(readr)
library(tibble)
library(cmdstanr)
library(mrmr)
library(ggpubr)
```

**Load and format data**

```{r}

surveys <- read.csv("/Users/johnimperato/Desktop/Mossy-Pond/data/survey_MossyPond.csv")
captures <- read.csv("/Users/johnimperato/Documents/private_MP_data/captures_MP.csv")

mp_data <- mrmr::clean_data(captures, surveys)
  
```

**Fit the custom model to MP data and summarize**

```{r}

# Fit the custom model using the modified function
custom_mod_MP <- fit_model_custom(mp_custom_data,
                                chains = 3, 
                                iter_sampling = 1000, 
                                iter_warmup = 400)

custom_mod_mp_summary <- custom_mod_MP$m_fit$summary()
View(custom_mod_mp_summary)

write.csv(custom_mod_mp_summary, "/Users/johnimperato/Desktop/Mossy-Pond_companion/mp_custom_mod_summary.csv")

```

**Plot abundance and recruitment**

```{r}

abundance_MP_custom <- mrmr::plot_model(custom_mod_MP, "abundance")
recruitment_MP_custom <- mrmr::plot_model(custom_mod_MP, "recruitment")

mp_custom_plots <- ggarrange(abundance_MP_custom, recruitment_MP_custom, ncol=1)

# add title
mp_custom_plots_annotated <- annotate_figure(mp_custom_plots, top = text_grob("Custom mrmr", size = 14, face = "bold"))

mp_custom_plots_annotated

```

### Model Comparison – custom/classic

#### Generated Quantities

*Parameter comparison table*

```{r}
# pull generated quantities from model fit summary
N_classic <- classic_mod_54188_summary[, c(1,2,4)]
N_custom <- custom_mod_54188_summary[33659:33674, c(1,2,4)]
B_classic <- classic_mod_54188_summary[4221:4225, c(1,2,4)]
B_custom <- custom_mod_54188_summary[33676:33691, c(1,2,4)]
Phi_classic <- classic_mod_54188_summary[4240:4243, c(1,2,4)]
Phi_custom <- custom_mod_54188_summary[33739:33753, c(1,2,4)]
p_classic <- classic_mod_54188_summary[4226:4239, c(1,2,4)]
p_custom <- custom_mod_54188_summary[33692:33738, c(1,2,4)]
  
GenQuant_comparison_mp <- bind_rows(
  left_join(N_classic, N_custom, by = "variable", suffix = c("_classic", "_custom")) %>% mutate(parameter = "abundance"),
  left_join(B_classic, B_custom, by = "variable", suffix = c("_classic", "_custom")) %>% mutate(parameter = "recruitment"),
  left_join(Phi_classic, Phi_custom, by = "variable", suffix = c("_classic", "_custom")) %>% mutate(parameter = "survival"),
  left_join(p_classic, p_custom, by = "variable", suffix = c("_classic", "_custom")) %>% mutate(parameter = "detection"),
) %>% 
  select(variable, parameter, everything())

print(GenQuant_comparison_mp)

# Convert table to grob (graphical object)
table_grob <- tableGrob(GenQuant_comparison_mp)

# Save as an image
ggsave("/Users/johnimperato/Desktop/Mossy-Pond/out/MP_comparison_table.png", plot = table_grob, width = 8, height = 10)

```

**Abundance/Recruitment comparison plot**
Note that axes are not standardized.

```{r}
# visual comparison of abundance and recruitment plots
abund_recruit_comparison_plot_mp <- ggarrange(mp_classic_plots_annotated, mp_custom_plots_annotated, ncol=2)
print(abund_recruit_comparison_plot_mp)

```

#### Model Fit

**LOO comparison**

```{r}
loo_classic <- classic_mod_54188$m_fit$loo()

loo_custom <- custom_mod_54188$m_fit$loo()

loo_compare <- loo::loo_compare(loo_classic, loo_custom)

print(loo_compare)

# extract elpd_diff and se_diff for model1
elpd_diff_model1 <- loo_compare["model1", "elpd_diff"]
se_diff_model1 <- loo_compare["model1", "se_diff"]

# calculate significance ratio
result <- abs(elpd_diff_model1 / se_diff_model1)

# interpret
if (abs(result) > 2) {
  cat("The absolute value of elpd_diff / se_diff for model1:", result, "\n")
  cat("The custom model fits the data significantly better than the classic model.\n")
} else {
  cat("The absolute value of elpd_diff / se_diff for model1:", result, "\n")
  cat("The custom model does not fit the data significantly better than the classic model.\n")
}

```
